### ISSUE TITLE
What if all rewards are the same? np.std will return 0.0 and rewards will be nan 

### ISSUE THREAD

**Issue by pushnyakov** [alirezamika/evostra#5]
https://github.com/alirezamika/evostra/blob/3819a3c1e9f16a99e90f874c141fddb3e26f18e9/evostra/algorithms/evolution_strategy.py#L58

**Comment by alirezamika** [comment]
We can add a little noise to rewards in this scenario.

**Comment by pushnyakov** [comment]
Actually, it is very easy to find a case when rewards may not change a lot. For example, if we have chosen sigma in the wrong way, then this is very likely for rewards to be the same. 
I suggest to skip this population and do not use it in updating weights. Something like:
```python
            rewards = np.array(rewards)
            std = np.std(rewards)
            if std > 0:

              rewards = (rewards - np.mean(rewards)) / np.std(rewards)

              for index, w in enumerate(self.weights):
                  A = np.array([p[index] for p in population])
                  self.weights[index] = w + self.LEARNING_RATE / (self.POPULATION_SIZE * self.SIGMA) * np.dot(A.T,
                                                                                                              rewards).T

              self.LEARNING_RATE *= self.decay

              if (iteration + 1) % print_step == 0:
                  print('iter %d. reward: %f' % (iteration + 1, self.get_reward(self.weights)))
```

**Comment by alirezamika** [comment]
Yea, also the get_reward function shoud be chosen wisely; It should have a proper and continuous feedback on improvements. 
I’m not sure what we can do about it in the code here. 
Maybe a warning and suggestion about possible solutions?

**Comment by pushnyakov** [comment]
> Yea, also the get_reward function shoud be chosen wisely; It should have a proper and continuous feedback on improvements.

I agree, but if our space is piecewise constant at some point we have problems.
A warning is OK, but optimization routine should not giving us nans since reaching some plateau in the parameters space.

**Comment by rajcscw** [comment]
Is this step needed at all `rewards = (rewards - np.mean(rewards)) / np.std(rewards) ` ?

I understand why it is required, but I'm wondering, why was not this mentioned in the paper? Or am i missing something?

**Comment by pushnyakov** [comment]
> Is this step needed at all rewards = (rewards - np.mean(rewards)) / np.std(rewards) ?

>I understand why it is required, but I'm wondering, why was not this mentioned in the paper? Or am i missing something?

As far as I understand rewards should not necessarily be sampled from N(0, I) distribution. 
But it improves the results in the following way: it removes the importance of outliers (which can be really big outliers), so the distribution of returns became more "smooth".

**Comment by alirezamika** [comment]
I changed the updating weights section to the model specified in the paper. The changes are in the refactor branch.
The nan problem will be solved.

**Comment by rajcscw** [comment]
I'm working on the implementation of ES for a different application and noticed that without normalizing of rewards `rewards = (rewards - np.mean(rewards)) / np.std(rewards)`, there is no learning at all. 

Also, by reading the paper, they mentioned that they apply rank transformation of rewards before applying parameter update. So, I think this rescaling of rewards is a crucial step which affects learning, espcially if the reward function is monotically varying.
